### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by Metsanpeitto**
The feature that I have implemented in this branch is:
- Improve the look and feel of the application, adding the styles of your choice.

### CODE REVIEW

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hi @Metsanpeitto, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you're working on your same branches of your last week.
Kindly provide new branches for your weekly tasks.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Metsanpeitto** [comment]
Hi @carlos-ssh ! 
Hei, can you explain me what was the problem? 
I created this branch just for fitting the style that I already implemented before. 
How can I do to submit?

**Comment by carlos-ssh** [comment]
> Hi @carlos-ssh !
> Hei, can you explain me what was the problem?
> I created this branch just for fitting the style that I already implemented before.
> How can I do to submit?

Create a new pull request with your old code.

**Comment by Metsanpeitto** [comment]
That's my old code. I just created a new branch for it. I have already merged the last branch "hit-api-branch" so I cannot present it again for a code review.
Sorry, but I'm not getting it. What do I have to do?

**Review by mikenath223 — APPROVED** [review]
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
